version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./htdocs/tw/:/var/www/html
    ports: 
      - "8080:80"
    restart: always
    env_file: .env

volumes:
  db_data: